### ISSUE TITLE
Rebase to 1.8.7

### ISSUE THREAD

**Issue by TiTo-418** [twizmwazin/CardinalPGM#689]
Cardinal doesn't work on SportBukkit 1.8.7

**Comment by dentmaged** [comment]
@TiTo-418 Logs?

**Comment by TiTo-418** [comment]
@dentmaged http://www.mediafire.com/download/o0xrh9cw1nwzdy3/2015-06-09-2.log

**Comment by dentmaged** [comment]
The issue is to do with Playable, line 32, a null pointer exception.

**Comment by ryanw-se** [comment]
@dentmaged That isn't what is causing this issue. The problem is Cardinal hard codes NBT rather than using reflection, it appears that some of these paths have changed in the SportBukkit 1.8.7 rebase. There are several of these errors through out the program, however you can reflect on this code snippet as a brief example.

```
[10:53:37] [Server thread/WARN]: java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R1/Packet
[10:53:37] [Server thread/WARN]: 	at in.twizmwaz.cardinal.module.modules.bossBar.BossBarBuilder.load(BossBarBuilder.java:10)
[10:53:37] [Server thread/WARN]: 	at in.twizmwaz.cardinal.module.ModuleFactory.build(ModuleFactory.java:199)
[10:53:37] [Server thread/WARN]: 	at in.twizmwaz.cardinal.match.Match.registerModules(Match.java:49)
[10:53:37] [Server thread/WARN]: 	at in.twizmwaz.cardinal.GameHandler.cycleAndMakeMatch(GameHandler.java:52)
[10:53:37] [Server thread/WARN]: 	at in.twizmwaz.cardinal.GameHandler$1.run(GameHandler.java:36)
[10:53:37] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:53)
[10:53:37] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:349)
[10:53:37] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:696)
[10:53:37] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:335)
[10:53:37] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:645)
[10:53:37] [Server thread/WARN]: 	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:555)
[10:53:37] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
[10:53:37] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_8_R1.Packet
[10:53:37] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:72)
[10:53:37] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:67)
[10:53:37] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[10:53:37] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[10:53:37] [Server thread/WARN]: 	... 12 more
```

**Comment by dentmaged** [comment]
@ryanw-se There are multiple issues, one of them is that.

**Comment by ryanw-se** [comment]
:+1:  @dentmaged The way you worded your post, was done in a fashion that lead me to believe that you thought that was the only issue. Might want to choose better wording in the future. :-)

**Comment by twizmwazin** [comment]
The update should just be NMS tweaks, I'm planing on doing it as soon as I get home. New API in SportBukkit should allow me to remove *most* of the NMS, although that will come at a later date.

**Comment by twizmwazin** [comment]
@ryanw-se I do not consider it important nor worthwhile to maintain compatibility with old versions. I will make a single commit, at which point 1.8.0 support will be discontinued. There is no reason to remain using 1.8.0 after Cardinal has updated.

**Comment by ryanw-se** [comment]
@twizmwazin This update really isn't stated anywhere, so I suspect that a large amount of your users will still attempt to run the newer versions of Cardinal built for the rebase, on their older SportBukkit software. 

Perhaps implementing some sort of alert system for server administrators that provides more in depth about important changes like this should be implemented. At least that way you will be able to give your users a notice ahead of time and they can coordinate accordingly.

**Comment by TiTo-418** [comment]
Maybe you can change this https://github.com/twizmwazin/CardinalNotifications/blob/master/update.json

**Comment by twizmwazin** [comment]
@ryanw-se 

`[15:43:47 WARN]: [CardinalPGM] ########################################
[15:43:47 WARN]: [CardinalPGM] #####  YOUR VERSION OF SPORTBUKKIT #####
[15:43:47 WARN]: [CardinalPGM] #####  IS NOT SUPPORTED. PLEASE    #####
[15:43:47 WARN]: [CardinalPGM] #####  USE  SPORTBUKKIT 1.8.0      #####
[15:43:47 WARN]: [CardinalPGM] ########################################
`
That is the current message in the latest version as of now. I'm about to do the update, and it will be changed to say 1.8.7.

**Comment by ryanw-se** [comment]
@twizmwazin If you look at the log posted in the in the ticket, that message was never sent.

**Comment by twizmwazin** [comment]
@ryanw-se Huh, worked for me. I'll look into it.

**Comment by twizmwazin** [comment]
Done in 4f2c1093b13f68734f13a0cb317324050ce24f93. Let us know if there are any new issues so we can fix them soon.

**Comment by TiTo-418** [comment]
@twizmwazin No, all works perfect
